version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "5000:5000"
    environment:
      # Pipeline & CI Configuration
      - GITHUB_TOKEN=${GITHUB_TOKEN:-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}  # GitHub Personal Access Token
      - JENKINS_URL=${JENKINS_URL}  # Optional: Jenkins server URL
      - JENKINS_JOB=${JENKINS_JOB}  # Optional: Jenkins job name
      - JENKINS_USER=${JENKINS_USER}  # Optional: Jenkins username
      - JENKINS_TOKEN=${JENKINS_TOKEN}  # Optional: Jenkins API token
      - DOCKERHUB_REPO=${DOCKERHUB_REPO}  # Your DockerHub repo for images
      - DOCKERHUB_USER=${spidey005}  # DockerHub username
      - DOCKERHUB_PASS=${Sangle@123}  # DockerHub password/token
      # K8s Configuration (optional)
      - K8S_DEPLOYMENT=user-service
      - K8S_NAMESPACE=default
      # Monitoring URLs
      - PROMETHEUS_URL=http://prometheus:9090
      - GRAFANA_URL=http://grafana:3000
      - JENKINS_URL=${JENKINS_URL}  # Optional: Jenkins integration
    depends_on:
      - prometheus
      - grafana

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
